service: event-bridge-test

frameworkVersion: "3"

custom:
  stage: ${opt:stage, self:provider.stage}
  esbuild:
    minify: true
  # NOTE: For normal usage, replace the following dynamic name with your static bus name
  eventBusName: ${self:service}-${self:custom.stage}-message-test
  prune:
    automatic: true
    number: 3
  tableName: event-bridge-test-stack-events

provider:
  architecture: arm64
  deploymentBucket:
    name: com.reference-architecture.deploys
    serverSideEncryption: AES256
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
    LOG_LEVEL: DEBUG
    NODE_ENV: ${self:custom.stage}
    SAMPLE_DEBUG_LOG_RATE: "1"
    TABLE_NAME: ${self:custom.tableName}
  logRetentionInDays: 7
  name: aws
  region: us-east-1
  runtime: nodejs20.x
  stage: dev
  tags:
    lumigo:auto-trace: "true"

functions:
  writeMessages:
    handler: src/messageWriter.default
    events:
      - eventBridge:
          # For your normal usage, you would use the next line for your existing bus ARN
          # eventBus: arn:aws:events:${self:provider.region}:123456789:event-bus/${self:custom.eventBusName}
          eventBus: !Ref TestEventBus
          pattern:
            source:
              - com.your-app.test
            detail-type:
              - new
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:PutItem
        Resource: !Sub arn:aws:dynamodb:${self:provider.region}:${AWS::AccountId}:table/${self:custom.tableName}
resources:
  Resources:
    # NOTE - you likely won't do the following, but will instead use your existing Event Bus.
    #  This just allows us to dynamically demonstrate the test.
    TestEventBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: ${self:custom.eventBusName}

    TestEventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

plugins:
  - serverless-esbuild
  - serverless-prune-plugin
  - serverless-iam-roles-per-function
  - serverless-deployment-bucket
