service: event-bridge-test

custom:
  stage: ${opt:stage, self:provider.stage}
  # NOTE: For normal usage, replace the following dynamic name with your static bus name
  eventBusName: ${self:service}-${self:custom.stage}-message-test

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  environment:
    NODE_ENV: ${self:custom.stage}
    LOG_LEVEL: DEBUG
    SAMPLE_DEBUG_LOG_RATE: '1'
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
  tags:
    'lumigo:auto-trace': true
  eventBridge:
    useCloudFormation: true
  deploymentBucket:
    name: com.reference-architecture.deploys
    serverSideEncryption: AES256
 
functions:
  writeMessages:
    handler: src/messageWriter.handler
    events:
      - eventBridge:
          # For your normal usage, you would use the next line for your existing bus ARN
          # eventBus: arn:aws:events:${self:provider.region}:123456789:event-bus/${self:custom.eventBusName}
          eventBus: !Ref TestEventBus
          pattern:
            source:
              - com.your-app.test
            detail-type:
              - new

# NOTE - you likely won't do the following, but will instead use your existing Event Bus.
#  This just allows us to dynamically demonstrate the test.
resources:
  Resources:
    TestEventBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: ${self:custom.eventBusName}
           
plugins:
  - serverless-plugin-typescript
  - serverless-deployment-bucket